### ISSUE TITLE
[Bug] 部分高分辨率图片无法上传

### ISSUE THREAD

**Issue by keaiye** [MliKiowa/GithubFile#13]
最新master
PHP Version：8.0
![image](https://user-images.githubusercontent.com/43440669/132671383-2ebf60a7-8a2f-463c-a745-f89fd13bbe55.png)

[09-09-18-36.log](https://github.com/MliKiowa/GithubFile/files/7135828/09-09-18-36.log)

**Comment by MliKiowa** [comment]
emm 稍后我看看

**Comment by MliKiowa** [comment]
未能日志捕获到上传部分 具体情况我下次复现看看
仅仅捕获了一处attachmenthandle
所以我建议进群或者QQ/telegram联系我下
tip: 普通仓库文件50mb将无法上传

**Comment by MliKiowa** [comment]
dev分支在最近一个月会尝试修复这个问题
