### ISSUE TITLE
ver-1.1.0 更新计划进度规划

### ISSUE THREAD

**Issue by MliKiowa** [MliKiowa/GithubFile#18]
在 2022/6 1.1.0版本计划开发中

**Comment by MliKiowa** [comment]
done
1.已经引入Basic认证 去掉oauth或者token模式

**Comment by MliKiowa** [comment]
to do
1.日志系统与错误追踪优化
now problem
1.PHP8标准规范发生不向下兼容

**Comment by MliKiowa** [comment]
鸽几个月再说

**Comment by notetoday** [comment]
现在不能用了吗？

**Comment by MliKiowa** [comment]
> 现在不能用了吗？

具体状态我也不太清楚 不过应该是可以用的 请自行使用personal token填写秘钥就行

**Comment by MliKiowa** [comment]
> 会有报错，而且文档提到的授权文件也没有看见有下载的地方

那能留下你的IM账号嘛

**Comment by notetoday** [comment]
我添加了946735494，不过没有同意

**Comment by MliKiowa** [comment]
> 
因为咱换了QQ是946735494
