### ISSUE TITLE
[Bug] Ver 1.4.0 Que 问题收集

### ISSUE THREAD

**Issue by MliKiowa** [MliKiowa/GithubFile#26]
**Describe the question**
在下面描述问题

**Comment by MliKiowa** [comment]
疑似低版本Typecho无法正常识别插件

**Comment by Mitpoppy** [comment]
可否上传图片时自动压缩图片，并且是可选开关、可选压缩率

**Comment by Mitpoppy** [comment]
可否上传图片时自动压缩图片，并且是可选开关、可选压缩率

**Comment by Mitpoppy** [comment]
可否上传图片时自动压缩图片，并且是可选开关、可选压缩率

**Comment by GWen124** [comment]
GithubFile | Use GitHub Repos To Update Attachment | 1.3.3 | Mlikiowa | 即插即用

没有设置选项

**Comment by MliKiowa** [comment]
> GithubFile | Use GitHub Repos To Update Attachment | 1.3.3 | Mlikiowa | 即插即用
> 
> 没有设置选项

请问你的typecho版本是

**Comment by Mitpoppy** [comment]
话说。。。你用着Hexo维护着typecho博客的插件是什么鬼🌚

**Comment by MliKiowa** [comment]
> 话说。。。你用着Hexo维护着typecho博客的插件是什么鬼🌚

总不能放着不管吧 偶尔更新小插件也不是很累

**Comment by MliKiowa** [comment]
> 话说。。。你用着Hexo维护着typecho博客的插件是什么鬼🌚

hexo比typecho轻松很多的 （放在ghpages就开摆了

**Comment by MliKiowa** [comment]
> GithubFile | Use GitHub Repos To Update Attachment | 1.3.3 | Mlikiowa | 即插即用
> 
> 没有设置选项

低版本typecho或php可能不支持最新规范写的插件

**Comment by Mitpoppy** [comment]
> > 话说。。。你用着Hexo维护着typecho博客的插件是什么鬼🌚
> 
> hexo比typecho轻松很多的 （放在ghpages就开摆了

gh+hexo感觉上传写文章什么的比较麻烦

**Comment by MliKiowa** [comment]
> > > 话说。。。你用着Hexo维护着typecho博客的插件是什么鬼🌚
> > 
> > 
> > hexo比typecho轻松很多的 （放在ghpages就开摆了
> 
> gh+hexo感觉上传写文章什么的比较麻烦

用工具先写好文章 然后上传也是很方便的

**Comment by Mitpoppy** [comment]
> > > > 话说。。。你用着Hexo维护着typecho博客的插件是什么鬼🌚
> > > 
> > > 
> > > hexo比typecho轻松很多的 （放在ghpages就开摆了
> > 
> > gh+hexo感觉上传写文章什么的比较麻烦
> 
> 用工具先写好文章 然后上传也是很方便的

我typecho花钱买的handsome不舍得换🌚

**Comment by GWen124** [comment]
> > GithubFile | Use GitHub Repos To Update Attachment | 1.3.3 | Mlikiowa | 即插即用
> 
> > 
> 
> > 没有设置选项
> 
> 
> 
> 请问你的typecho版本是

由 Typecho 强力驱动, 版本 1.2 (18.10.23)

**Comment by GWen124** [comment]
> 疑似低版本Typecho无法正常识别插件

能修复吗？我用的void主题，最新版不兼容

**Comment by MliKiowa** [comment]
> > 疑似低版本Typecho无法正常识别插件
> 
> 能修复吗？我用的void主题，最新版不兼容

我过几天看看能不能复现下

**Comment by MliKiowa** [comment]
> > > > > 话说。。。你用着Hexo维护着typecho博客的插件是什么鬼🌚
> > > > 
> > > > 
> > > > hexo比typecho轻松很多的 （放在ghpages就开摆了
> > > 
> > > 
> > > gh+hexo感觉上传写文章什么的比较麻烦
> > 
> > 
> > 用工具先写好文章 然后上传也是很方便的
> 
> 我typecho花钱买的handsome不舍得换🌚

这倒是 不过服务器我已经付不起了

**Comment by Mitpoppy** [comment]
> > > > > > 话说。。。你用着Hexo维护着typecho博客的插件是什么鬼🌚
> > > > > 
> > > > > 
> > > > > hexo比typecho轻松很多的 （放在ghpages就开摆了
> > > > 
> > > > 
> > > > gh+hexo感觉上传写文章什么的比较麻烦
> > > 
> > > 
> > > 用工具先写好文章 然后上传也是很方便的
> > 
> > 我typecho花钱买的handsome不舍得换🌚
> 
> 这倒是 不过服务器我已经付不起了

我这里有一台nat服务器，为了开博客又买了一台1h1g🤣

**Comment by lynnguo666-personal** [comment]
似乎无法删除图片，使用Typecho 1.2
以及希望增加一个设置，支持选择上传到服务器/上传到Github
这个选项在插件设置里实现

**Comment by Mitpoppy** [comment]
> 以及希望增加一个单独页面，显示上传至Github的文件

实际上你如果只是想要单独上传一个文件可以直接去github上传，或者是在编辑文章页面上传之后复制链接

**Comment by lynnguo666-personal** [comment]
> > 以及希望增加一个单独页面，显示上传至Github的文件
> 
> 实际上你如果只是想要单独上传一个文件可以直接去github上传，或者是在编辑文章页面上传之后复制链接

主要是希望能制作一个类似
<img width="932" alt="image" src="https://user-images.githubusercontent.com/39556167/210966164-e954d88e-7867-41e1-9d2c-990ad2c37486.png">
的管理页面，或者是类似Typecho原生的文件管理 可以修改文件名字 描述什么的，这样可以方便管理一些，以及图片的复用

**Comment by Mitpoppy** [comment]
> > > 以及希望增加一个单独页面，显示上传至Github的文件
> > 
> > 实际上你如果只是想要单独上传一个文件可以直接去github上传，或者是在编辑文章页面上传之后复制链接
> 
> 主要是希望能制作一个类似
> <img width="932" alt="image" src="https://user-images.githubusercontent.com/39556167/210966164-e954d88e-7867-41e1-9d2c-990ad2c37486.png">
> 的管理页面，或者是类似Typecho原生的文件管理 可以修改文件名字 描述什么的，这样可以方便管理一些，以及图片的复用
> 

哇哦这个不错🌝

**Comment by GWen124** [comment]
发现两个问题。启动插件后一个是后台控制台进入个人设置报错，而一个是管理-文件里 删除或者清理未归档文件报错

**Comment by GWen124** [comment]
禁用插件后 插件日志选项还在控制台里面

**Comment by MliKiowa** [comment]
> 禁用插件后 插件日志选项还在控制台里面

插件蹦掉了应该

**Comment by MliKiowa** [comment]
> 发现两个问题。启动插件后一个是后台控制台进入个人设置报错，而一个是管理-文件里 删除或者清理未归档文件报错

这个问题修好了

**Comment by cyolc932** [comment]
> > 发现两个问题。启动插件后一个是后台控制台进入个人设置报错，而一个是管理-文件里 删除或者清理未归档文件报错
> 
> 这个问题修好了

请问为什么上传的图片会自动变成数字命名...我给本地图片命名好了想上传上去保持原命名 可以实现这个吗

例如 新的截图.jpg 上传后变成了 数字.jpg

我想让它 新的截图.jpg 上传后保持原命名 新的截图.jpg

**Comment by MliKiowa** [comment]
> 

我看看

**Comment by cyolc932** [comment]
这是来自邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by cyolc932** [comment]
> > 
> 
> 我看看

另外有个小问题 上传后好像不能立即跳出是否插入的那个框
我使用这个插件 从你刚发布到现在 
感觉上传好像不是很稳定 
就是单个1mb以内的图片上传的时候它就会跳这个是否插入框
当文件两个或两个以上的时候就开始出现小问题了
如果你不点存为草稿 那些上传记录就会丢失
如果恰到好处 刚好GitHub那边上传完毕 你点了存为草稿 一切正常 但还是有概率出现下面这种情况

上传60个文件 typecho只显示49个 缺少一部分...

**Comment by MliKiowa** [comment]
> > > 
> > 
> > 
> > 我看看
> 
> 另外有个小问题 上传后好像不能立即跳出是否插入的那个框
> 
> 我使用这个插件 从你刚发布到现在 感觉上传好像不是很稳定 就是单个1mb以内的图片上传的时候它就会跳这个是否插入框
> 
> 当文件两个或两个以上的时候就开始出现小问题了
> 
> 如果你不点存为草稿 那些上传记录就会丢失 如果恰到好处 刚好GitHub那边上传完毕 你点了存为草稿 一切正常 但还是有概率出现下面这种情况
> 
> 上传60个文件 typecho只显示49个 缺少一部分...

这是我的qq 1627126029 具体你可以加我 然后我具体看看

**Comment by cyolc932** [comment]
> > > > 
> > > 
> > > 
> > > 我看看
> > 
> > 
> > 另外有个小问题 上传后好像不能立即跳出是否插入的那个框
> > 我使用这个插件 从你刚发布到现在 感觉上传好像不是很稳定 就是单个1mb以内的图片上传的时候它就会跳这个是否插入框
> > 当文件两个或两个以上的时候就开始出现小问题了
> > 如果你不点存为草稿 那些上传记录就会丢失 如果恰到好处 刚好GitHub那边上传完毕 你点了存为草稿 一切正常 但还是有概率出现下面这种情况
> > 上传60个文件 typecho只显示49个 缺少一部分...
> 
> 这是我的qq 1627126029 具体你可以加我 然后我具体看看

我之后只能去GitHub删除这60个文件 然后删除typecho上的文件记录49个记录
接着第二次重新上传 的时候我打开typecho的文件页面一直刷新
等到它60个记录都有了才点存为草稿 

之后就很少多图片上传了 一篇文章最多五张图

**Comment by MliKiowa** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 我看看
> > > 
> > > 
> > > 另外有个小问题 上传后好像不能立即跳出是否插入的那个框
> > > 我使用这个插件 从你刚发布到现在 感觉上传好像不是很稳定 就是单个1mb以内的图片上传的时候它就会跳这个是否插入框
> > > 当文件两个或两个以上的时候就开始出现小问题了
> > > 如果你不点存为草稿 那些上传记录就会丢失 如果恰到好处 刚好GitHub那边上传完毕 你点了存为草稿 一切正常 但还是有概率出现下面这种情况
> > > 上传60个文件 typecho只显示49个 缺少一部分...
> > 
> > 
> > 这是我的qq 1627126029 具体你可以加我 然后我具体看看
> 
> 这是去年12月的时候的测试
> 
> 我之后用了个方法解决 只能去GitHub删除这60个文件 然后删除typecho上的文件记录49个记录
> 
> 接着第二次重新上传的时候 我打开typecho的文件页面一直刷新 等到它60个记录 确认都有了 才点存为草稿
> 
> 之后就很少多图片上传了 一篇文章最多五张图

应该是Github的限制 插件只能尽量优化

**Comment by cyolc932** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 我看看
> > > > 
> > > > 
> > > > 另外有个小问题 上传后好像不能立即跳出是否插入的那个框
> > > > 我使用这个插件 从你刚发布到现在 感觉上传好像不是很稳定 就是单个1mb以内的图片上传的时候它就会跳这个是否插入框
> > > > 当文件两个或两个以上的时候就开始出现小问题了
> > > > 如果你不点存为草稿 那些上传记录就会丢失 如果恰到好处 刚好GitHub那边上传完毕 你点了存为草稿 一切正常 但还是有概率出现下面这种情况
> > > > 上传60个文件 typecho只显示49个 缺少一部分...
> > > 
> > > 
> > > 这是我的qq 1627126029 具体你可以加我 然后我具体看看
> > 
> > 
> > 这是去年12月的时候的测试
> > 我之后用了个方法解决 只能去GitHub删除这60个文件 然后删除typecho上的文件记录49个记录
> > 接着第二次重新上传的时候 我打开typecho的文件页面一直刷新 等到它60个记录 确认都有了 才点存为草稿
> > 之后就很少多图片上传了 一篇文章最多五张图
> 
> 应该是Github的限制 插件只能尽量优化

从Github推送的上传记录上看 是单个文件一个一个的上传的 
要是可以一次性同时上传 我觉得估计可以解决这个问题

**Comment by cyolc932** [comment]
![图片](https://github.com/MliKiowa/GithubFile/assets/46415893/ae29c743-70da-4b57-a21c-12bbf3138bba)
好像查未成功  https://github.com/MliKiowa/GithubFile/pull/38

**Comment by MliKiowa** [comment]
> ![图片](https://user-images.githubusercontent.com/46415893/238190635-ae29c743-70da-4b57-a21c-12bbf3138bba.png) 好像检查未成功 #38

别急 我估计要明天或者后天才能修好 并且在这几周折腾一个全新版本 优化多图片 压缩问题

**Comment by cyolc932** [comment]
> > ![图片](https://user-images.githubusercontent.com/46415893/238190635-ae29c743-70da-4b57-a21c-12bbf3138bba.png) 好像检查未成功 #38
> 
> 别急 我估计要明天或者后天才能修好 并且在这几周折腾一个全新版本 优化多图片 压缩问题

最近传的很多 就是怕滥用GitHub和jsdelivr 会被ban库 有点想放弃GitHub做博客图床了 准备另寻他法

**Comment by Mitpoppy** [comment]
> > > ![图片](https://user-images.githubusercontent.com/46415893/238190635-ae29c743-70da-4b57-a21c-12bbf3138bba.png) 好像检查未成功 #38
> > 
> > 别急 我估计要明天或者后天才能修好 并且在这几周折腾一个全新版本 优化多图片 压缩问题
> 
> 最近传的很多 就是怕滥用GitHub和jsdelivr 会被ban库 有点想放弃GitHub做博客图床了 准备另寻他法
> 

别用图片不就完了，文字的 blog 依然可以生动有趣🙃

**Comment by cyolc932** [comment]
> > > > ![图片](https://user-images.githubusercontent.com/46415893/238190635-ae29c743-70da-4b57-a21c-12bbf3138bba.png) 好像检查未成功 #38
> > > 
> > > 
> > > 别急 我估计要明天或者后天才能修好 并且在这几周折腾一个全新版本 优化多图片 压缩问题
> > 
> > 
> > 最近传的很多 就是怕滥用GitHub和jsdelivr 会被ban库 有点想放弃GitHub做博客图床了 准备另寻他法
> 
> 别用图片不就完了，文字的 blog 依然可以生动有趣🙃

做了个中转 继续存在github上 不过访问资源是用服务器流量缓存 应该能避免滥用github

**Comment by MliKiowa** [comment]
> > > > > ![图片](https://user-images.githubusercontent.com/46415893/238190635-ae29c743-70da-4b57-a21c-12bbf3138bba.png) 好像检查未成功 #38
> > > > 
> > > > 
> > > > 别急 我估计要明天或者后天才能修好 并且在这几周折腾一个全新版本 优化多图片 压缩问题
> > > 
> > > 
> > > 最近传的很多 就是怕滥用GitHub和jsdelivr 会被ban库 有点想放弃GitHub做博客图床了 准备另寻他法
> > 
> > 
> > 别用图片不就完了，文字的 blog 依然可以生动有趣🙃
> 
> 做了个中转 继续存在github上 不过访问资源是用服务器流量缓存 应该能避免滥用github

我的建议是别太过分是可以的 做好备份是其中一件事

**Comment by MliKiowa** [comment]
> > > > ![图片](https://user-images.githubusercontent.com/46415893/238190635-ae29c743-70da-4b57-a21c-12bbf3138bba.png) 好像检查未成功 #38
> > > 
> > > 
> > > 别急 我估计要明天或者后天才能修好 并且在这几周折腾一个全新版本 优化多图片 压缩问题
> > 
> > 
> > 最近传的很多 就是怕滥用GitHub和jsdelivr 会被ban库 有点想放弃GitHub做博客图床了 准备另寻他法
> 
> 别用图片不就完了，文字的 blog 依然可以生动有趣🙃

说起来你可能不信 最近这个库的pr优化代码全是ai生成的 aifix分支是我目前正在修改的

**Comment by Mitpoppy** [comment]
> > > > > ![图片](https://user-images.githubusercontent.com/46415893/238190635-ae29c743-70da-4b57-a21c-12bbf3138bba.png) 好像检查未成功 #38
> > > > 
> > > > 
> > > > 别急 我估计要明天或者后天才能修好 并且在这几周折腾一个全新版本 优化多图片 压缩问题
> > > 
> > > 
> > > 最近传的很多 就是怕滥用GitHub和jsdelivr 会被ban库 有点想放弃GitHub做博客图床了 准备另寻他法
> > 
> > 别用图片不就完了，文字的 blog 依然可以生动有趣🙃
> 
> 说起来你可能不信 最近这个库的pr优化代码全是ai生成的 aifix分支是我目前正在修改的

怪不得看代码写的这么标准，不像你的风格🙃

**Comment by MliKiowa** [comment]
> > > > > > ![图片](https://user-images.githubusercontent.com/46415893/238190635-ae29c743-70da-4b57-a21c-12bbf3138bba.png) 好像检查未成功 #38
> > > > > 
> > > > > 
> > > > > 别急 我估计要明天或者后天才能修好 并且在这几周折腾一个全新版本 优化多图片 压缩问题
> > > > 
> > > > 
> > > > 最近传的很多 就是怕滥用GitHub和jsdelivr 会被ban库 有点想放弃GitHub做博客图床了 准备另寻他法
> > > 
> > > 
> > > 别用图片不就完了，文字的 blog 依然可以生动有趣🙃
> > 
> > 
> > 说起来你可能不信 最近这个库的pr优化代码全是ai生成的 aifix分支是我目前正在修改的
> 
> 怪不得看代码写的这么标准，不像你的风格🙃

最近提交的commit都是有注释的 然后我也是让ai大幅优化了逻辑的 而我写的话没有typecho环境而且很随意所以是这样

**Comment by MliKiowa** [comment]
> > > > > ![图片](https://user-images.githubusercontent.com/46415893/238190635-ae29c743-70da-4b57-a21c-12bbf3138bba.png) 好像检查未成功 #38
> > > > 
> > > > 
> > > > 别急 我估计要明天或者后天才能修好 并且在这几周折腾一个全新版本 优化多图片 压缩问题
> > > 
> > > 
> > > 最近传的很多 就是怕滥用GitHub和jsdelivr 会被ban库 有点想放弃GitHub做博客图床了 准备另寻他法
> > 
> > 
> > 别用图片不就完了，文字的 blog 依然可以生动有趣🙃
> 
> 做了个中转 继续存在github上 不过访问资源是用服务器流量缓存 应该能避免滥用github

目前 #39 aifix分支已经进入1.4.0 并且支持了你之前的提议 我预计两天内把它测试下放到main分支
