### ISSUE TITLE
使用netlify进行github的仓库加速

### ISSUE THREAD

**Issue by hunkill** [MliKiowa/GithubFile#31]
![image](https://user-images.githubusercontent.com/45861843/212267572-a866a18c-8a8e-4936-ba6c-e22fb0820276.png)
实际路劲为：域名/GithubFile/2023/01/13/1673595487.jpg
但输出路径为：域名/用户名/仓库名/GithubFile/2023/01/13/1673595487.jpg
请我要如何修改输出

**Comment by MliKiowa** [comment]
你应该试试修改插件源码了或者等待我的更新



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月13日 15:57 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [MliKiowa/GithubFile] 使用netlify进行github的仓库加速 (Issue #31) |


实际路劲为：域名/GithubFile/2023/01/13/1673595487.jpg
但输出路径为：域名/用户名/仓库名/GithubFile/2023/01/13/1673595487.jpg
请我要如何修改输出

**Comment by MliKiowa** [comment]
#30 在这个分支一同处理这个问题

**Comment by MliKiowa** [comment]
https://github.com/MliKiowa/GithubFile/blob/cb788b4016b3d38f01d5160e401541ba18e3dba7/Handler.php#L54
这里是核心逻辑

**Comment by hunkill** [comment]
> https://github.com/MliKiowa/GithubFile/blob/cb788b4016b3d38f01d5160e401541ba18e3dba7/Handler.php#L122
> 
> 
> 这里是核心总辑
![image](https://user-images.githubusercontent.com/45861843/212507861-fdbdc7ba-c1a2-42de-a19b-847c973bcccf.png)




![image](https://user-images.githubusercontent.com/45861843/212506881-3976ca0c-88d6-4b2c-8bfa-684f5ad943d2.png)


嗯，可以了可以用了
不过填写File_Mirror时得去掉末尾/
不然会：域名//

**Comment by MliKiowa** [comment]
OK 这个最近我也会主动更新支持的



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月15日 09:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [MliKiowa/GithubFile] 使用netlify进行github的仓库加速 (Issue #31) |

https://github.com/MliKiowa/GithubFile/blob/cb788b4016b3d38f01d5160e401541ba18e3dba7/Handler.php#L122

这里是核心总辑


嗯，可以了可以用了
不过填写File_Mirror时得去掉末尾/
不然会：域名//

**Comment by MliKiowa** [comment]
我已经写好了大部分 预计明天支持你的想法

**Comment by MliKiowa** [comment]
对了能留个QQ联系吗 我这有点事关于插件的

**Comment by hunkill** [comment]
qq：2298191256

**Comment by MliKiowa** [comment]
问题已经解决
