### ISSUE TITLE
[Bug] 境内服务器上传图片之后不返回图片路径

### ISSUE THREAD

**Issue by yj920** [MliKiowa/GithubFile#9]
如题，国外服务器使用正常
大陆服务器可以上传图片，但是上传后不会返回图床链接

**Comment by MliKiowa** [comment]
版本是多少呢
如果有时间联系我
因为插件还在测试 希望你的参与
QQ:946735494

**Comment by MliKiowa** [comment]
你使用新版本试试 我更新了下
